server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backend?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345qqaa

